### ISSUE TITLE
Table breaks when used with align="center"

### ISSUE THREAD

**Issue by pnacht** [jrowen/rhandsontable#365]
The following code gives the expected output:

```r
library(shiny)
library(rhandsontable)

ui <- function() {
  fluidPage(
    fluidRow(
      column(12,
             # align = "center",
             rHandsontableOutput("test")
             )
    )
  )
}

server <- function(input, output, session) {
  output$test <- renderRHandsontable(
    rhandsontable(
      data.frame(a = 1:2, b = 2:3)
    )
  )
}

shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/15221358/94825990-35c9b780-03dd-11eb-8cf8-927331b8db8d.png)

However, if we uncomment the `align = "center"`, it breaks:

```r
ui <- function() {
  fluidPage(
    fluidRow(
      column(12,
             align = "center",
             rHandsontableOutput("test")
             )
    )
  )
}
```

![image](https://user-images.githubusercontent.com/15221358/94826139-63166580-03dd-11eb-9222-1c57ef1a37b3.png)

The above is using the RStudio renderer, but the same happens when opening on Chrome.

**Comment by Alik-V** [comment]
@sametsoekel running into that issue now. Have you managed to develop a workaround for this? 
Tried doing it through CSS but the result is the same:
```css
.wtHider { 
    margin: auto;
    width: auto;
}
```
![image](https://user-images.githubusercontent.com/43731270/149118880-058d4abd-527a-496e-8f16-5914d8b39088.png)

**Comment by sametsoekel** [comment]
@Alik-V yes, I fixed that issue. I just passed `rowHeaders = NULL` to my rhandsontable object. Let here know if this works for you also, the developer may see and fix the bug.

**Comment by Alik-V** [comment]
Ah great, much appreciate the help!

Worked for me with the combination of the CSS above

**Comment by Flocondeneige55** [comment]
@Alik-V : Could you paste a reprex of the code with the CSS combination which worked for you? I can't seem to get it to work unfortunately, the whole table gets shifted to the right with a horizontal scrollbar appearing, instead of centring.

**Comment by Alik-V** [comment]
> @Alik-V : Could you paste a reprex of the code with the CSS combination which worked for you? I can't seem to get it to work unfortunately, the whole table gets shifted to the right with a horizontal scrollbar appearing, instead of centring.

Oh god, this was a while ago. The only internal linked commits I can find in my private repo use this:

```css
              .wtHider { 
                margin: auto;
                width: auto;
              }
```
**or** this:
```css
              .ht_master handsontable { 
    margin-left: auto;
    margin-right: auto;
}
```

Not sure if it was the exact fix
